### ISSUE TITLE
api not resolve properly when using api.WithEndpoint

### ISSUE THREAD

**Issue by ahmadnurus** [micro/go-api#10]
I took the example from https://github.com/micro/examples/tree/master/api/meta but i change the path from `/example` to `/call`

```go
	// register example handler
	proto.RegisterExampleHandler(service.Server(), new(Example), api.WithEndpoint(&api.Endpoint{
		// The RPC method
		Name: "Example.Call",
		// The HTTP paths. This can be a POSIX regex
		Path: []string{"/call"},
		// The HTTP Methods for this endpoint
		Method: []string{"POST"},
		// The API handler to use
		Handler: rpc.Handler,
	}))
```

it is normal when I access `http://localhost:8080/call`

```
$ curl -H 'Content-Type: application/json' -d '{"name": "john"}' "http://localhost:8080/call"
{
  "message": "got your request john"
}
```

but when I add one or more paths before `call`, it is resolve to `Example.Call` method too

```
$ curl -H 'Content-Type: application/json' -d '{"name": "john"}' "http://localhost:8080/foo/bar/call"
{
  "message": "got your request john"
}
```
thanks

**Comment by asim** [comment]
This is because as mentioned in the comment, its POSIX regex matching. This can be on any partial path matching. To scope it only to /path use "^/path$"

**Comment by ahmadnurus** [comment]
Thanks asim, i have not tried it with POSIX
