### ISSUE TITLE
go get will  casue error when using of go module

### ISSUE THREAD

**Issue by Linnkenn** [micro/go-api#11]
E:\GoStudy\pkg\mod\github.com\micro\micro@v0.14.0\internal\handler\meta.go:35:7: undefined: web.Handler
E:\GoStudy\pkg\mod\github.com\micro\micro@v0.14.0\internal\handler\meta.go:38:16: undefined: "github.com/micro/go-api/handler/http".Handler
E:\GoStudy\pkg\mod\github.com\micro\micro@v0.14.0\internal\handler\meta.go:41:7: undefined: rpc.Handler
E:\GoStudy\pkg\mod\github.com\micro\micro@v0.14.0\internal\handler\meta.go:44:7: undefined: event.Handler
E:\GoStudy\pkg\mod\github.com\micro\micro@v0.14.0\internal\handler\meta.go:50:7: undefined: "github.com/micro/go-api/handler/api".Handler

can you tag v0.3.2 to fix this bug? because micro@v0.14.0 use  aweb.Handler and go-api@0.3.1 don't have the definition.

**Comment by asim** [comment]
Tag 0.4.0 has been created.
