### ISSUE TITLE
Question on Limiting API access to signed in users

### ISSUE THREAD

**Issue by zhongliangong** [micro/go-api#2]
I took a look at the documentation in the Readme and the micro.mu site, but there did not seem to be anything written about securing the API gateway with OAuth2.

- I did see an auth-srv repository. Would the go-api client call this service for authentication before passing the request to the back end (or are there plans to extend it to do so)?
- Are there any plans to use JWT to allow each microservice to individually authenticate users without making another call to the authentication service?

Thank you once again and keep up the good work!

**Comment by asim** [comment]
Auth is a pretty complex topic which is implemented differently by everyone. The micro api is purposely agnostic of it. The toolkit has a plugin interface which you can specify a http.Handler to https://micro.mu/docs/plugins-toolkit.html. You can implement something that would parse JWT tokens or call out to some Oauth2 service. 

To answer your questions:

1. There is no plan to officially embed requests to auth-srv.
2. There are no plans to include JWT support.

Thanks
