### ISSUE TITLE
Is it possible to route websocket events to http requests?

### ISSUE THREAD

**Issue by gigi** [micro/go-api#26]
Hi!
Is it possible to use micro as WebSocket Api Gateway? 

Im looking for some solution that able to hold the persistent connection with the client and translate client's events to HTTP requests and send responses back to client.
```
client  <-- ws connection -->  ws gateway api  <-- http request --> backend
```
If I understand correctly this example  https://github.com/micro/examples/tree/master/stream shows only how to proxy the connection to other websocket server.

Thanx!

**Comment by asim** [comment]
You can use the web handler. Specify via --handler=web or via running the `micro web` component.
