### ISSUE TITLE
why not "pair" , but "map<string, Pair>" ?

### ISSUE THREAD

**Issue by super-organism** [micro/go-api#8]
hello ,i just have some confusion to this file https://github.com/micro/go-api/blob/master/proto/api.proto;
why are you don't direct to use "Pair" to define "header、get、post" ,but use "map<string, Pair> header",
i think this way is unnecessary;so i need your help me, thinks!

**Comment by asim** [comment]
It's a design decision from 3 years ago. It provides easy access to header keys
